# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SQ_Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SQ_Dialog(object):
    def setupUi(self, SQ_Dialog):
        """
        Set up the user interface for the Security Question Dialog.
        
        Args:
            SQ_Dialog (QDialog): The dialog to set up
        """
        SQ_Dialog.setObjectName("SQ_Dialog")
        SQ_Dialog.setFixedSize(640, 480)
        SQ_Dialog.setStyleSheet("""
            QDialog {
                background-color: #f5f5f5;
            }
        """)
        
        # Create header label
        self.header_label = QtWidgets.QLabel(SQ_Dialog)
        self.header_label.setGeometry(QtCore.QRect(0, 20, 640, 60))
        title_font = QtGui.QFont()
        title_font.setFamily("Arial")
        title_font.setPointSize(36)  # Increased font size
        title_font.setBold(True)
        self.header_label.setFont(title_font)
        self.header_label.setStyleSheet("color: #2c3e50;")
        self.header_label.setAlignment(QtCore.Qt.AlignCenter)
        self.header_label.setObjectName("header_label")
        self.header_label.setText("Security Question")  # Set text directly
        
        # Add exit button in top right corner
        self.exit_button = QtWidgets.QPushButton(SQ_Dialog)
        self.exit_button.setObjectName("exit_button")
        self.exit_button.setGeometry(QtCore.QRect(590, 10, 40, 40))
        self.exit_button.setMinimumSize(40, 40)
        self.exit_button.setMaximumSize(40, 40)
        self.exit_button.setStyleSheet("""
            QPushButton {
                background-color: #e74c3c;
                color: white;
                border-radius: 20px;
                font-weight: bold;
                font-size: 16px;
            }
            QPushButton:hover {
                background-color: #c0392b;
            }
            QPushButton:pressed {
                background-color: #a93226;
            }
        """)
        self.exit_button.setText("X")
        self.exit_button.setToolTip("Exit Application")
        
        self.security_answer = QtWidgets.QLineEdit(SQ_Dialog)
        self.security_answer.setGeometry(QtCore.QRect(190, 300, 381, 51))
        self.security_answer.setObjectName("security_answer")
        self.question_label = QtWidgets.QLabel(SQ_Dialog)
        self.question_label.setGeometry(QtCore.QRect(20, 180, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.question_label.setFont(font)
        self.question_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.question_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.question_label.setObjectName("question_label")
        self.answer_label = QtWidgets.QLabel(SQ_Dialog)
        self.answer_label.setGeometry(QtCore.QRect(20, 310, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.answer_label.setFont(font)
        self.answer_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.answer_label.setObjectName("answer_label")
        self.description_label = QtWidgets.QLabel(SQ_Dialog)
        self.description_label.setEnabled(True)
        self.description_label.setGeometry(QtCore.QRect(60, 90, 531, 121))
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(14)
        self.description_label.setFont(font)
        self.description_label.setText("")
        self.description_label.setWordWrap(True)
        self.description_label.setObjectName("description_label")
        self.OK_Button = QtWidgets.QPushButton(SQ_Dialog)
        self.OK_Button.setGeometry(QtCore.QRect(300, 410, 89, 25))
        self.OK_Button.setObjectName("OK_Button")

        self.nameUi(SQ_Dialog)
        QtCore.QMetaObject.connectSlotsByName(SQ_Dialog)

    def nameUi(self, SQ_Dialog):
        SQ_Dialog.setWindowTitle("Cypress")
        self.question_label.setText("Your Question:")
        self.answer_label.setText("Your Answer:")
        self.OK_Button.setText("OK")